package polylib;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class enode {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected enode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(enode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      PolylibJNI.delete_enode(swigCPtr);
    }
    swigCPtr = 0;
  }

  public enode_type getType() {
    return enode_type.swigToEnum(PolylibJNI.enode_type_get(swigCPtr));
  }

  public int getSize() {
    return PolylibJNI.enode_size_get(swigCPtr);
  }

  public int getPos() {
    return PolylibJNI.enode_pos_get(swigCPtr);
  }

  public evalue getArr() {
    long cPtr = PolylibJNI.enode_arr_get(swigCPtr);
    return (cPtr == 0) ? null : new evalue(cPtr, false);
  }

  public enode() {
    this(PolylibJNI.new_enode3(), true);
  }

}
