package polylib;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class enode_type {
  public final static enode_type polynomial = new enode_type("polynomial");
  public final static enode_type periodic = new enode_type("periodic");
  public final static enode_type evector = new enode_type("evector");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static enode_type swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + enode_type.class + " with value " + swigValue);
  }

  private enode_type(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private enode_type(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private enode_type(String swigName, enode_type swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static enode_type[] swigValues = { polynomial, periodic, evector };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

