package polylib;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Enumeration {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Enumeration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Enumeration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      PolylibJNI.delete_Enumeration(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Polyhedron getValidityDomain() {
    long cPtr = PolylibJNI.Enumeration_ValidityDomain_get(swigCPtr);
    return (cPtr == 0) ? null : new Polyhedron(cPtr, false);
  }

  public evalue getEP() {
    long cPtr = PolylibJNI.Enumeration_EP_get(swigCPtr);
    return (cPtr == 0) ? null : new evalue(cPtr, false);
  }

  public Enumeration getNext() {
    long cPtr = PolylibJNI.Enumeration_next_get(swigCPtr);
    return (cPtr == 0) ? null : new Enumeration(cPtr, false);
  }

  public Enumeration() {
    this(PolylibJNI.new_Enumeration(), true);
  }

}
