package polylib;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class evalue {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected evalue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(evalue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      PolylibJNI.delete_evalue(swigCPtr);
    }
    swigCPtr = 0;
  }

  public int getD() {
    return PolylibJNI.evalue_d_get(swigCPtr);
  }

  public evalue_x getX() {
    long cPtr = PolylibJNI.evalue_x_get(swigCPtr);
    return (cPtr == 0) ? null : new evalue_x(cPtr, false);
  }

  public evalue() {
    this(PolylibJNI.new_evalue(), true);
  }

}
