package polylib;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class evalue_x {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected evalue_x(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(evalue_x obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      PolylibJNI.delete_evalue_x(swigCPtr);
    }
    swigCPtr = 0;
  }

  public int getN() {
    return PolylibJNI.evalue_x_n_get(swigCPtr);
  }

  public enode getP() {
    long cPtr = PolylibJNI.evalue_x_p_get(swigCPtr);
    return (cPtr == 0) ? null : new enode(cPtr, false);
  }

  public evalue_x() {
    this(PolylibJNI.new_evalue_x(), true);
  }

}
