# nmake -f makefile.win32

polylib_home = /root/Download/polylib-5.22.3
CC = gcc

all:
	$(CC) -c swig_wrap.c -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/linux -I$(polylib_home)/include
	$(CC) -shared swig_wrap.o $(polylib_home)/.libs/libpolylib32.a   -o libpolylib32.so
	cp -f libpolylib32.so /usr/lib                          

clean:
	-rm  -f *.class *.h *.exe *.obj *.pdb *.exp *.lib *.exp *.ilk *.tst *.bak *.log
	
cleanall:clean
	-rm  -f *.manifest *.dll *.so
