package polylib;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Matrix {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Matrix(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Matrix obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      PolylibJNI.delete_Matrix(swigCPtr);
    }
    swigCPtr = 0;
  }

  public long getNbRows() {
    return PolylibJNI.Matrix_NbRows_get(swigCPtr);
  }

  public long getNbColumns() {
    return PolylibJNI.Matrix_NbColumns_get(swigCPtr);
  }

  public SWIGTYPE_p_p_int getP() {
    long cPtr = PolylibJNI.Matrix_p_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_int(cPtr, false);
  }


  public SWIGTYPE_p_int getP_Init() {
	  /*
	   * 
JNIEXPORT jlong JNICALL Java_polylib_PolylibJNI_Matrix_1p_1Init_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  Matrix *arg1 = (Matrix *) 0 ;
  Value *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Matrix **)&jarg1; 
  result = (Value *) ((arg1)->p_Init);
  *(Value **)&jresult = result; 
  return jresult;
 }
	   */
    long cPtr = PolylibJNI.Matrix_p_Init_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public int getP_Init_size() {
    return PolylibJNI.Matrix_p_Init_size_get(swigCPtr);
  }

  public Matrix() {
    this(PolylibJNI.new_Matrix(), true);
  }
  
  public Matrix(long cptr){
	  swigCPtr=cptr;
  }

}
