package polylib;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Param_Vertices {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Param_Vertices(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Param_Vertices obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      PolylibJNI.delete_Param_Vertices(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Matrix getVertex() {
    long cPtr = PolylibJNI.Param_Vertices_Vertex_get(swigCPtr);
    return (cPtr == 0) ? null : new Matrix(cPtr, false);
  }

  public Matrix getDomain() {
    long cPtr = PolylibJNI.Param_Vertices_Domain_get(swigCPtr);
    return (cPtr == 0) ? null : new Matrix(cPtr, false);
  }

  public Param_Vertices getNext() {
    long cPtr = PolylibJNI.Param_Vertices_next_get(swigCPtr);
    return (cPtr == 0) ? null : new Param_Vertices(cPtr, false);
  }

  public Param_Vertices() {
    this(PolylibJNI.new_Param_Vertices(), true);
  }

}
