package polylib;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Param_Domain {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Param_Domain(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Param_Domain obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      PolylibJNI.delete_Param_Domain(swigCPtr);
    }
    swigCPtr = 0;
  }

  public SWIGTYPE_p_unsigned_int getF() {
    long cPtr = PolylibJNI.Param_Domain_F_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public Polyhedron getDomain() {
    long cPtr = PolylibJNI.Param_Domain_Domain_get(swigCPtr);
    return (cPtr == 0) ? null : new Polyhedron(cPtr, false);
  }

  public Param_Domain getNext() {
    long cPtr = PolylibJNI.Param_Domain_next_get(swigCPtr);
    return (cPtr == 0) ? null : new Param_Domain(cPtr, false);
  }

  public Param_Domain() {
    this(PolylibJNI.new_Param_Domain(), true);
  }

}
