package polylib;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface PolylibConstants {
  public final static int POLYLIB_BITS = PolylibJNI.POLYLIB_BITS_get();
  public final static long __LONG_LONG_MAX__ = PolylibJNI.__LONG_LONG_MAX___get();
  public final static long LONG_LONG_MAX = PolylibJNI.LONG_LONG_MAX_get();
  public final static long LONG_LONG_MIN = PolylibJNI.LONG_LONG_MIN_get();
  public final static java.math.BigInteger ULONG_LONG_MAX = PolylibJNI.ULONG_LONG_MAX_get();
  public final static String LINEAR_VALUE_STRING = PolylibJNI.LINEAR_VALUE_STRING_get();
  public final static String VALUE_FMT = PolylibJNI.VALUE_FMT_get();
  public final static int VALUE_ZERO = PolylibJNI.VALUE_ZERO_get();
  public final static int VALUE_ONE = PolylibJNI.VALUE_ONE_get();
  public final static int VALUE_MONE = PolylibJNI.VALUE_MONE_get();
  public final static String __CURRENT_FUNCTION_NAME__ = PolylibJNI.__CURRENT_FUNCTION_NAME___get();
  public final static char FIRST_PARAMETER_NAME = PolylibJNI.FIRST_PARAMETER_NAME_get();
  public final static char PCHAR = PolylibJNI.PCHAR_get();
  public final static int MAXNOOFRAYS = PolylibJNI.MAXNOOFRAYS_get();
  public final static String P_VALUE_FMT = PolylibJNI.P_VALUE_FMT_get();
  public final static int LB_INFINITY = PolylibJNI.LB_INFINITY_get();
  public final static int UB_INFINITY = PolylibJNI.UB_INFINITY_get();
  public final static int POL_INEQUALITIES = PolylibJNI.POL_INEQUALITIES_get();
  public final static int POL_FACETS = PolylibJNI.POL_FACETS_get();
  public final static int POL_POINTS = PolylibJNI.POL_POINTS_get();
  public final static int POL_VERTICES = PolylibJNI.POL_VERTICES_get();
  public final static int POL_VALID = PolylibJNI.POL_VALID_get();
}
