package polylib;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ZPolyhedron {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ZPolyhedron(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ZPolyhedron obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      PolylibJNI.delete_ZPolyhedron(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Matrix getLat() {
    long cPtr = PolylibJNI.ZPolyhedron_Lat_get(swigCPtr);
    return (cPtr == 0) ? null : new Matrix(cPtr, false);
  }

  public Polyhedron getP() {
    long cPtr = PolylibJNI.ZPolyhedron_P_get(swigCPtr);
    return (cPtr == 0) ? null : new Polyhedron(cPtr, false);
  }

  public ZPolyhedron getNext() {
    long cPtr = PolylibJNI.ZPolyhedron_next_get(swigCPtr);
    return (cPtr == 0) ? null : new ZPolyhedron(cPtr, false);
  }

  public ZPolyhedron() {
    this(PolylibJNI.new_ZPolyhedron(), true);
  }

}
