/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cloog;

public class cloogblocklist {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected cloogblocklist(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cloogblocklist obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      CLooGJNI.delete_cloogblocklist(swigCPtr);
    }
    swigCPtr = 0;
  }

  public cloogblock getBlock() {
    long cPtr = CLooGJNI.cloogblocklist_block_get(swigCPtr);
    return (cPtr == 0) ? null : new cloogblock(cPtr, false);
  }

  public cloogblocklist getNext() {
    long cPtr = CLooGJNI.cloogblocklist_next_get(swigCPtr);
    return (cPtr == 0) ? null : new cloogblocklist(cPtr, false);
  }

  public cloogblocklist() {
    this(CLooGJNI.new_cloogblocklist(), true);
  }

}
