/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cloog;

public class cloognames {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected cloognames(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cloognames obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      CLooGJNI.delete_cloognames(swigCPtr);
    }
    swigCPtr = 0;
  }

  public int getNb_scalars() {
    return CLooGJNI.cloognames_nb_scalars_get(swigCPtr);
  }

  public int getNb_scattering() {
    return CLooGJNI.cloognames_nb_scattering_get(swigCPtr);
  }

  public int getNb_iterators() {
    return CLooGJNI.cloognames_nb_iterators_get(swigCPtr);
  }

  public int getNb_parameters() {
    return CLooGJNI.cloognames_nb_parameters_get(swigCPtr);
  }

  public SWIGTYPE_p_p_char getScalars() {
    long cPtr = CLooGJNI.cloognames_scalars_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public SWIGTYPE_p_p_char getScattering() {
    long cPtr = CLooGJNI.cloognames_scattering_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public SWIGTYPE_p_p_char getIterators() {
    long cPtr = CLooGJNI.cloognames_iterators_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public SWIGTYPE_p_p_char getParameters() {
    long cPtr = CLooGJNI.cloognames_parameters_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public cloognames() {
    this(CLooGJNI.new_cloognames(), true);
  }

}
