/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cloog;

public class cloogdomainlist {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected cloogdomainlist(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cloogdomainlist obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      CLooGJNI.delete_cloogdomainlist(swigCPtr);
    }
    swigCPtr = 0;
  }

  public cloogdomain getDomain() {
    long cPtr = CLooGJNI.cloogdomainlist_domain_get(swigCPtr);
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public cloogdomainlist getNext() {
    long cPtr = CLooGJNI.cloogdomainlist_next_get(swigCPtr);
    return (cPtr == 0) ? null : new cloogdomainlist(cPtr, false);
  }

  public cloogdomainlist() {
    this(CLooGJNI.new_cloogdomainlist(), true);
  }

}
