/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cloog;

public class CLooG implements CLooGConstants {
  public static SWIGTYPE_p_FILE getStdin() {
    long cPtr = CLooGJNI.stdin_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static SWIGTYPE_p_FILE getStdout() {
    long cPtr = CLooGJNI.stdout_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static SWIGTYPE_p_FILE getStderr() {
    long cPtr = CLooGJNI.stderr_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static int printf(String _Format) {
    return CLooGJNI.printf(_Format);
  }

  public static SWIGTYPE_p_FILE fopen(String arg0, String arg1) {
    long cPtr = CLooGJNI.fopen(arg0, arg1);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static int fclose(SWIGTYPE_p_FILE arg0) {
    return CLooGJNI.fclose(SWIGTYPE_p_FILE.getCPtr(arg0));
  }

  public static void cloog_options_print(SWIGTYPE_p_FILE arg0, cloogoptions arg1) {
    CLooGJNI.cloog_options_print(SWIGTYPE_p_FILE.getCPtr(arg0), cloogoptions.getCPtr(arg1));
  }

  public static void cloog_options_free(cloogoptions arg0) {
    CLooGJNI.cloog_options_free(cloogoptions.getCPtr(arg0));
  }

  public static void cloog_options_read(int arg0, SWIGTYPE_p_p_char arg1, SWIGTYPE_p_p_FILE arg2, SWIGTYPE_p_p_FILE arg3, SWIGTYPE_p_p_cloogoptions arg4) {
    CLooGJNI.cloog_options_read(arg0, SWIGTYPE_p_p_char.getCPtr(arg1), SWIGTYPE_p_p_FILE.getCPtr(arg2), SWIGTYPE_p_p_FILE.getCPtr(arg3), SWIGTYPE_p_p_cloogoptions.getCPtr(arg4));
  }

  public static cloogoptions cloog_options_malloc() {
    long cPtr = CLooGJNI.cloog_options_malloc();
    return (cPtr == 0) ? null : new cloogoptions(cPtr, false);
  }

  public static void cloog_matrix_print(SWIGTYPE_p_FILE arg0, SWIGTYPE_p_Matrix arg1) {
    CLooGJNI.cloog_matrix_print(SWIGTYPE_p_FILE.getCPtr(arg0), SWIGTYPE_p_Matrix.getCPtr(arg1));
  }

  public static void cloog_matrix_free(SWIGTYPE_p_Matrix arg0) {
    CLooGJNI.cloog_matrix_free(SWIGTYPE_p_Matrix.getCPtr(arg0));
  }

  public static SWIGTYPE_p_Matrix cloog_matrix_alloc(long arg0, long arg1) {
    long cPtr = CLooGJNI.cloog_matrix_alloc(arg0, arg1);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Matrix(cPtr, false);
  }

  public static SWIGTYPE_p_Matrix cloog_matrix_matrix(SWIGTYPE_p_Matrix arg0) {
    long cPtr = CLooGJNI.cloog_matrix_matrix(SWIGTYPE_p_Matrix.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Matrix(cPtr, false);
  }

  public static void cloog_matrix_print_structure(SWIGTYPE_p_FILE arg0, SWIGTYPE_p_Matrix arg1, int arg2) {
    CLooGJNI.cloog_matrix_print_structure(SWIGTYPE_p_FILE.getCPtr(arg0), SWIGTYPE_p_Matrix.getCPtr(arg1), arg2);
  }

  public static SWIGTYPE_p_Matrix cloog_matrix_read(SWIGTYPE_p_FILE arg0) {
    long cPtr = CLooGJNI.cloog_matrix_read(SWIGTYPE_p_FILE.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Matrix(cPtr, false);
  }

  public static void cloog_matrix_normalize(SWIGTYPE_p_Matrix arg0, int arg1) {
    CLooGJNI.cloog_matrix_normalize(SWIGTYPE_p_Matrix.getCPtr(arg0), arg1);
  }

  public static void cloog_matrix_equality_update(SWIGTYPE_p_Matrix arg0, int arg1, int arg2) {
    CLooGJNI.cloog_matrix_equality_update(SWIGTYPE_p_Matrix.getCPtr(arg0), arg1, arg2);
  }

  public static SWIGTYPE_p_Matrix cloog_matrix_copy(SWIGTYPE_p_Matrix arg0) {
    long cPtr = CLooGJNI.cloog_matrix_copy(SWIGTYPE_p_Matrix.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Matrix(cPtr, false);
  }

  public static SWIGTYPE_p_Value cloog_matrix_vector_copy(SWIGTYPE_p_Value arg0, int arg1) {
    long cPtr = CLooGJNI.cloog_matrix_vector_copy(SWIGTYPE_p_Value.getCPtr(arg0), arg1);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Value(cPtr, false);
  }

  public static SWIGTYPE_p_Value cloog_matrix_vector_simplify(SWIGTYPE_p_Value arg0, SWIGTYPE_p_Matrix arg1, int arg2, int arg3, int arg4) {
    long cPtr = CLooGJNI.cloog_matrix_vector_simplify(SWIGTYPE_p_Value.getCPtr(arg0), SWIGTYPE_p_Matrix.getCPtr(arg1), arg2, arg3, arg4);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Value(cPtr, false);
  }

  public static SWIGTYPE_p_Matrix cloog_matrix_simplify(SWIGTYPE_p_Matrix arg0, SWIGTYPE_p_Matrix arg1, int arg2, int arg3) {
    long cPtr = CLooGJNI.cloog_matrix_simplify(SWIGTYPE_p_Matrix.getCPtr(arg0), SWIGTYPE_p_Matrix.getCPtr(arg1), arg2, arg3);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Matrix(cPtr, false);
  }

  public static void cloog_matrix_vector_free(SWIGTYPE_p_Value arg0, int arg1) {
    CLooGJNI.cloog_matrix_vector_free(SWIGTYPE_p_Value.getCPtr(arg0), arg1);
  }

  public static void cloog_value_leak_up() {
    CLooGJNI.cloog_value_leak_up();
  }

  public static void cloog_value_leak_down() {
    CLooGJNI.cloog_value_leak_down();
  }

  public static cloogdomain cloog_domain_matrix2domain(SWIGTYPE_p_Matrix arg0) {
    long cPtr = CLooGJNI.cloog_domain_matrix2domain(SWIGTYPE_p_Matrix.getCPtr(arg0));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static SWIGTYPE_p_Matrix cloog_domain_domain2matrix(cloogdomain arg0) {
    long cPtr = CLooGJNI.cloog_domain_domain2matrix(cloogdomain.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Matrix(cPtr, false);
  }

  public static void cloog_domain_print(SWIGTYPE_p_FILE arg0, cloogdomain arg1) {
    CLooGJNI.cloog_domain_print(SWIGTYPE_p_FILE.getCPtr(arg0), cloogdomain.getCPtr(arg1));
  }

  public static void cloog_polyhedron_print(SWIGTYPE_p_FILE arg0, SWIGTYPE_p_Polyhedron arg1) {
    CLooGJNI.cloog_polyhedron_print(SWIGTYPE_p_FILE.getCPtr(arg0), SWIGTYPE_p_Polyhedron.getCPtr(arg1));
  }

  public static void cloog_domain_free(cloogdomain arg0) {
    CLooGJNI.cloog_domain_free(cloogdomain.getCPtr(arg0));
  }

  public static cloogdomain cloog_domain_copy(cloogdomain arg0) {
    long cPtr = CLooGJNI.cloog_domain_copy(cloogdomain.getCPtr(arg0));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_image(cloogdomain arg0, SWIGTYPE_p_Matrix arg1) {
    long cPtr = CLooGJNI.cloog_domain_image(cloogdomain.getCPtr(arg0), SWIGTYPE_p_Matrix.getCPtr(arg1));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_preimage(cloogdomain arg0, SWIGTYPE_p_Matrix arg1) {
    long cPtr = CLooGJNI.cloog_domain_preimage(cloogdomain.getCPtr(arg0), SWIGTYPE_p_Matrix.getCPtr(arg1));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_convex(cloogdomain Pol) {
    long cPtr = CLooGJNI.cloog_domain_convex(cloogdomain.getCPtr(Pol));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_simple_convex(cloogdomain domain, int nb_par) {
    long cPtr = CLooGJNI.cloog_domain_simple_convex(cloogdomain.getCPtr(domain), nb_par);
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_simplify(cloogdomain arg0, cloogdomain arg1) {
    long cPtr = CLooGJNI.cloog_domain_simplify(cloogdomain.getCPtr(arg0), cloogdomain.getCPtr(arg1));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_union(cloogdomain arg0, cloogdomain arg1) {
    long cPtr = CLooGJNI.cloog_domain_union(cloogdomain.getCPtr(arg0), cloogdomain.getCPtr(arg1));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_disjoint(cloogdomain arg0) {
    long cPtr = CLooGJNI.cloog_domain_disjoint(cloogdomain.getCPtr(arg0));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_intersection(cloogdomain arg0, cloogdomain arg1) {
    long cPtr = CLooGJNI.cloog_domain_intersection(cloogdomain.getCPtr(arg0), cloogdomain.getCPtr(arg1));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_difference(cloogdomain arg0, cloogdomain arg1) {
    long cPtr = CLooGJNI.cloog_domain_difference(cloogdomain.getCPtr(arg0), cloogdomain.getCPtr(arg1));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static int cloog_domain_includes(cloogdomain arg0, cloogdomain arg1) {
    return CLooGJNI.cloog_domain_includes(cloogdomain.getCPtr(arg0), cloogdomain.getCPtr(arg1));
  }

  public static cloogdomain cloog_domain_addconstraints(cloogdomain arg0, cloogdomain arg1) {
    long cPtr = CLooGJNI.cloog_domain_addconstraints(cloogdomain.getCPtr(arg0), cloogdomain.getCPtr(arg1));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static void cloog_domain_sort(SWIGTYPE_p_p_Polyhedron arg0, long arg1, long arg2, long arg3, SWIGTYPE_p_int arg4) {
    CLooGJNI.cloog_domain_sort(SWIGTYPE_p_p_Polyhedron.getCPtr(arg0), arg1, arg2, arg3, SWIGTYPE_p_int.getCPtr(arg4));
  }

  public static cloogdomain cloog_domain_empty(int arg0) {
    long cPtr = CLooGJNI.cloog_domain_empty(arg0);
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static void cloog_domain_print_structure(SWIGTYPE_p_FILE arg0, cloogdomain arg1, int arg2) {
    CLooGJNI.cloog_domain_print_structure(SWIGTYPE_p_FILE.getCPtr(arg0), cloogdomain.getCPtr(arg1), arg2);
  }

  public static void cloog_domain_list_print(SWIGTYPE_p_FILE arg0, cloogdomainlist arg1) {
    CLooGJNI.cloog_domain_list_print(SWIGTYPE_p_FILE.getCPtr(arg0), cloogdomainlist.getCPtr(arg1));
  }

  public static void cloog_domain_list_free(cloogdomainlist arg0) {
    CLooGJNI.cloog_domain_list_free(cloogdomainlist.getCPtr(arg0));
  }

  public static cloogdomain cloog_domain_read(SWIGTYPE_p_FILE arg0) {
    long cPtr = CLooGJNI.cloog_domain_read(SWIGTYPE_p_FILE.getCPtr(arg0));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_union_read(SWIGTYPE_p_FILE arg0) {
    long cPtr = CLooGJNI.cloog_domain_union_read(SWIGTYPE_p_FILE.getCPtr(arg0));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomainlist cloog_domain_list_read(SWIGTYPE_p_FILE arg0) {
    long cPtr = CLooGJNI.cloog_domain_list_read(SWIGTYPE_p_FILE.getCPtr(arg0));
    return (cPtr == 0) ? null : new cloogdomainlist(cPtr, false);
  }

  public static cloogdomain cloog_domain_malloc() {
    long cPtr = CLooGJNI.cloog_domain_malloc();
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_alloc(SWIGTYPE_p_Polyhedron arg0) {
    long cPtr = CLooGJNI.cloog_domain_alloc(SWIGTYPE_p_Polyhedron.getCPtr(arg0));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_compact(cloogdomain arg0) {
    long cPtr = CLooGJNI.cloog_domain_compact(cloogdomain.getCPtr(arg0));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static int cloog_domain_isempty(cloogdomain arg0) {
    return CLooGJNI.cloog_domain_isempty(cloogdomain.getCPtr(arg0));
  }

  public static int cloog_domain_universe(cloogdomain arg0) {
    return CLooGJNI.cloog_domain_universe(cloogdomain.getCPtr(arg0));
  }

  public static cloogdomain cloog_domain_project(cloogdomain arg0, int arg1, int arg2) {
    long cPtr = CLooGJNI.cloog_domain_project(cloogdomain.getCPtr(arg0), arg1, arg2);
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_bounds(cloogdomain arg0, int arg1, int arg2) {
    long cPtr = CLooGJNI.cloog_domain_bounds(cloogdomain.getCPtr(arg0), arg1, arg2);
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_extend(cloogdomain arg0, int arg1, int arg2) {
    long cPtr = CLooGJNI.cloog_domain_extend(cloogdomain.getCPtr(arg0), arg1, arg2);
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static int cloog_domain_never_integral(cloogdomain arg0) {
    return CLooGJNI.cloog_domain_never_integral(cloogdomain.getCPtr(arg0));
  }

  public static void cloog_domain_stride(cloogdomain arg0, int arg1, int arg2, SWIGTYPE_p_Value arg3, SWIGTYPE_p_Value arg4) {
    CLooGJNI.cloog_domain_stride(cloogdomain.getCPtr(arg0), arg1, arg2, SWIGTYPE_p_Value.getCPtr(arg3), SWIGTYPE_p_Value.getCPtr(arg4));
  }

  public static int cloog_domain_integral_lowerbound(cloogdomain arg0, int arg1, SWIGTYPE_p_Value arg2) {
    return CLooGJNI.cloog_domain_integral_lowerbound(cloogdomain.getCPtr(arg0), arg1, SWIGTYPE_p_Value.getCPtr(arg2));
  }

  public static void cloog_domain_lowerbound_update(cloogdomain arg0, int arg1, SWIGTYPE_p_Value arg2) {
    CLooGJNI.cloog_domain_lowerbound_update(cloogdomain.getCPtr(arg0), arg1, SWIGTYPE_p_Value.getCPtr(arg2));
  }

  public static int cloog_domain_lazy_disjoint(cloogdomain arg0, cloogdomain arg1) {
    return CLooGJNI.cloog_domain_lazy_disjoint(cloogdomain.getCPtr(arg0), cloogdomain.getCPtr(arg1));
  }

  public static int cloog_domain_lazy_equal(cloogdomain arg0, cloogdomain arg1) {
    return CLooGJNI.cloog_domain_lazy_equal(cloogdomain.getCPtr(arg0), cloogdomain.getCPtr(arg1));
  }

  public static int cloog_domain_lazy_block(cloogdomain arg0, cloogdomain arg1, cloogdomainlist arg2, int arg3) {
    return CLooGJNI.cloog_domain_lazy_block(cloogdomain.getCPtr(arg0), cloogdomain.getCPtr(arg1), cloogdomainlist.getCPtr(arg2), arg3);
  }

  public static int cloog_domain_lazy_isscalar(cloogdomain arg0, int arg1) {
    return CLooGJNI.cloog_domain_lazy_isscalar(cloogdomain.getCPtr(arg0), arg1);
  }

  public static int cloog_domain_list_lazy_same(cloogdomainlist arg0) {
    return CLooGJNI.cloog_domain_list_lazy_same(cloogdomainlist.getCPtr(arg0));
  }

  public static void cloog_domain_scalar(cloogdomain arg0, int arg1, SWIGTYPE_p_Value arg2) {
    CLooGJNI.cloog_domain_scalar(cloogdomain.getCPtr(arg0), arg1, SWIGTYPE_p_Value.getCPtr(arg2));
  }

  public static cloogdomain cloog_domain_grow(cloogdomain arg0, int arg1, int arg2) {
    long cPtr = CLooGJNI.cloog_domain_grow(cloogdomain.getCPtr(arg0), arg1, arg2);
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_cut_first(cloogdomain arg0) {
    long cPtr = CLooGJNI.cloog_domain_cut_first(cloogdomain.getCPtr(arg0));
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static cloogdomain cloog_domain_erase_dimension(cloogdomain arg0, int arg1) {
    long cPtr = CLooGJNI.cloog_domain_erase_dimension(cloogdomain.getCPtr(arg0), arg1);
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public static void cloog_domain_reverse(cloogdomain arg0) {
    CLooGJNI.cloog_domain_reverse(cloogdomain.getCPtr(arg0));
  }

  public static void cloog_domain_line_update(SWIGTYPE_p_Polyhedron arg0, SWIGTYPE_p_Matrix arg1, int arg2, int arg3) {
    CLooGJNI.cloog_domain_line_update(SWIGTYPE_p_Polyhedron.getCPtr(arg0), SWIGTYPE_p_Matrix.getCPtr(arg1), arg2, arg3);
  }

  public static void cloog_statement_print_structure(SWIGTYPE_p_FILE arg0, cloogstatement arg1, int arg2) {
    CLooGJNI.cloog_statement_print_structure(SWIGTYPE_p_FILE.getCPtr(arg0), cloogstatement.getCPtr(arg1), arg2);
  }

  public static void cloog_statement_print(SWIGTYPE_p_FILE arg0, cloogstatement arg1) {
    CLooGJNI.cloog_statement_print(SWIGTYPE_p_FILE.getCPtr(arg0), cloogstatement.getCPtr(arg1));
  }

  public static void cloog_statement_free(cloogstatement arg0) {
    CLooGJNI.cloog_statement_free(cloogstatement.getCPtr(arg0));
  }

  public static cloogstatement cloog_statement_malloc() {
    long cPtr = CLooGJNI.cloog_statement_malloc();
    return (cPtr == 0) ? null : new cloogstatement(cPtr, false);
  }

  public static cloogstatement cloog_statement_alloc(int arg0) {
    long cPtr = CLooGJNI.cloog_statement_alloc(arg0);
    return (cPtr == 0) ? null : new cloogstatement(cPtr, false);
  }

  public static cloogstatement cloog_statement_copy(cloogstatement arg0) {
    long cPtr = CLooGJNI.cloog_statement_copy(cloogstatement.getCPtr(arg0));
    return (cPtr == 0) ? null : new cloogstatement(cPtr, false);
  }

  public static void cloog_statement_add(SWIGTYPE_p_p_cloogstatement arg0, SWIGTYPE_p_p_cloogstatement arg1, cloogstatement arg2) {
    CLooGJNI.cloog_statement_add(SWIGTYPE_p_p_cloogstatement.getCPtr(arg0), SWIGTYPE_p_p_cloogstatement.getCPtr(arg1), cloogstatement.getCPtr(arg2));
  }

  public static void cloog_block_print_structure(SWIGTYPE_p_FILE arg0, cloogblock arg1, int arg2) {
    CLooGJNI.cloog_block_print_structure(SWIGTYPE_p_FILE.getCPtr(arg0), cloogblock.getCPtr(arg1), arg2);
  }

  public static void cloog_block_print(SWIGTYPE_p_FILE arg0, cloogblock arg1) {
    CLooGJNI.cloog_block_print(SWIGTYPE_p_FILE.getCPtr(arg0), cloogblock.getCPtr(arg1));
  }

  public static void cloog_block_list_print(SWIGTYPE_p_FILE arg0, cloogblocklist arg1) {
    CLooGJNI.cloog_block_list_print(SWIGTYPE_p_FILE.getCPtr(arg0), cloogblocklist.getCPtr(arg1));
  }

  public static void cloog_block_free(cloogblock arg0) {
    CLooGJNI.cloog_block_free(cloogblock.getCPtr(arg0));
  }

  public static void cloog_block_list_free(cloogblocklist arg0) {
    CLooGJNI.cloog_block_list_free(cloogblocklist.getCPtr(arg0));
  }

  public static cloogblock cloog_block_malloc() {
    long cPtr = CLooGJNI.cloog_block_malloc();
    return (cPtr == 0) ? null : new cloogblock(cPtr, false);
  }

  public static cloogblock cloog_block_alloc(cloogstatement arg0, SWIGTYPE_p_Matrix arg1, int arg2, SWIGTYPE_p_Value arg3, int arg4) {
    long cPtr = CLooGJNI.cloog_block_alloc(cloogstatement.getCPtr(arg0), SWIGTYPE_p_Matrix.getCPtr(arg1), arg2, SWIGTYPE_p_Value.getCPtr(arg3), arg4);
    return (cPtr == 0) ? null : new cloogblock(cPtr, false);
  }

  public static cloogblocklist cloog_block_list_malloc() {
    long cPtr = CLooGJNI.cloog_block_list_malloc();
    return (cPtr == 0) ? null : new cloogblocklist(cPtr, false);
  }

  public static cloogblocklist cloog_block_list_alloc(cloogblock arg0) {
    long cPtr = CLooGJNI.cloog_block_list_alloc(cloogblock.getCPtr(arg0));
    return (cPtr == 0) ? null : new cloogblocklist(cPtr, false);
  }

  public static cloogblock cloog_block_copy(cloogblock block) {
    long cPtr = CLooGJNI.cloog_block_copy(cloogblock.getCPtr(block));
    return (cPtr == 0) ? null : new cloogblock(cPtr, false);
  }

  public static void cloog_block_merge(cloogblock arg0, cloogblock arg1) {
    CLooGJNI.cloog_block_merge(cloogblock.getCPtr(arg0), cloogblock.getCPtr(arg1));
  }

  public static void cloog_names_print_structure(SWIGTYPE_p_FILE arg0, cloognames arg1, int arg2) {
    CLooGJNI.cloog_names_print_structure(SWIGTYPE_p_FILE.getCPtr(arg0), cloognames.getCPtr(arg1), arg2);
  }

  public static void cloog_names_print(SWIGTYPE_p_FILE arg0, cloognames arg1) {
    CLooGJNI.cloog_names_print(SWIGTYPE_p_FILE.getCPtr(arg0), cloognames.getCPtr(arg1));
  }

  public static void cloog_names_free(cloognames arg0) {
    CLooGJNI.cloog_names_free(cloognames.getCPtr(arg0));
  }

  public static SWIGTYPE_p_p_char cloog_names_read_strings(SWIGTYPE_p_FILE arg0, int arg1, String arg2, char arg3) {
    long cPtr = CLooGJNI.cloog_names_read_strings(SWIGTYPE_p_FILE.getCPtr(arg0), arg1, arg2, arg3);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public static cloognames cloog_names_malloc() {
    long cPtr = CLooGJNI.cloog_names_malloc();
    return (cPtr == 0) ? null : new cloognames(cPtr, false);
  }

  public static cloognames cloog_names_alloc(int arg0, int arg1, int arg2, int arg3, SWIGTYPE_p_p_char arg4, SWIGTYPE_p_p_char arg5, SWIGTYPE_p_p_char arg6, SWIGTYPE_p_p_char arg7) {
    long cPtr = CLooGJNI.cloog_names_alloc(arg0, arg1, arg2, arg3, SWIGTYPE_p_p_char.getCPtr(arg4), SWIGTYPE_p_p_char.getCPtr(arg5), SWIGTYPE_p_p_char.getCPtr(arg6), SWIGTYPE_p_p_char.getCPtr(arg7));
    return (cPtr == 0) ? null : new cloognames(cPtr, false);
  }

  public static SWIGTYPE_p_p_char cloog_names_generate_items(int arg0, String arg1, char arg2) {
    long cPtr = CLooGJNI.cloog_names_generate_items(arg0, arg1, arg2);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public static cloognames cloog_names_generate(int arg0, int arg1, int arg2, int arg3, char arg4, char arg5, char arg6, char arg7) {
    long cPtr = CLooGJNI.cloog_names_generate(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    return (cPtr == 0) ? null : new cloognames(cPtr, false);
  }

  public static void cloog_names_scalarize(cloognames arg0, int arg1, SWIGTYPE_p_int arg2) {
    CLooGJNI.cloog_names_scalarize(cloognames.getCPtr(arg0), arg1, SWIGTYPE_p_int.getCPtr(arg2));
  }

  public static void cloog_loop_print_structure(SWIGTYPE_p_FILE arg0, cloogloop arg1, int arg2) {
    CLooGJNI.cloog_loop_print_structure(SWIGTYPE_p_FILE.getCPtr(arg0), cloogloop.getCPtr(arg1), arg2);
  }

  public static void cloog_loop_print(SWIGTYPE_p_FILE arg0, cloogloop arg1) {
    CLooGJNI.cloog_loop_print(SWIGTYPE_p_FILE.getCPtr(arg0), cloogloop.getCPtr(arg1));
  }

  public static void cloog_loop_free(cloogloop arg0) {
    CLooGJNI.cloog_loop_free(cloogloop.getCPtr(arg0));
  }

  public static cloogloop cloog_loop_read(SWIGTYPE_p_FILE arg0, int arg1, int arg2) {
    long cPtr = CLooGJNI.cloog_loop_read(SWIGTYPE_p_FILE.getCPtr(arg0), arg1, arg2);
    return (cPtr == 0) ? null : new cloogloop(cPtr, false);
  }

  public static cloogloop cloog_loop_malloc() {
    long cPtr = CLooGJNI.cloog_loop_malloc();
    return (cPtr == 0) ? null : new cloogloop(cPtr, false);
  }

  public static cloogloop cloog_loop_generate(cloogloop arg0, cloogdomain arg1, int arg2, int arg3, SWIGTYPE_p_int arg4, int arg5, int arg6, cloogoptions arg7) {
    long cPtr = CLooGJNI.cloog_loop_generate(cloogloop.getCPtr(arg0), cloogdomain.getCPtr(arg1), arg2, arg3, SWIGTYPE_p_int.getCPtr(arg4), arg5, arg6, cloogoptions.getCPtr(arg7));
    return (cPtr == 0) ? null : new cloogloop(cPtr, false);
  }

  public static cloogloop cloog_loop_simplify(cloogloop arg0, cloogdomain arg1, int arg2, int arg3) {
    long cPtr = CLooGJNI.cloog_loop_simplify(cloogloop.getCPtr(arg0), cloogdomain.getCPtr(arg1), arg2, arg3);
    return (cPtr == 0) ? null : new cloogloop(cPtr, false);
  }

  public static void cloog_loop_scatter(cloogloop arg0, cloogdomain arg1) {
    CLooGJNI.cloog_loop_scatter(cloogloop.getCPtr(arg0), cloogdomain.getCPtr(arg1));
  }

  public static void cloog_program_print_structure(SWIGTYPE_p_FILE arg0, cloogprogram arg1, int arg2) {
    CLooGJNI.cloog_program_print_structure(SWIGTYPE_p_FILE.getCPtr(arg0), cloogprogram.getCPtr(arg1), arg2);
  }

  public static void cloog_program_print(SWIGTYPE_p_FILE arg0, cloogprogram arg1) {
    CLooGJNI.cloog_program_print(SWIGTYPE_p_FILE.getCPtr(arg0), cloogprogram.getCPtr(arg1));
  }

  public static void cloog_program_pprint(SWIGTYPE_p_FILE arg0, cloogprogram arg1, cloogoptions arg2) {
    CLooGJNI.cloog_program_pprint(SWIGTYPE_p_FILE.getCPtr(arg0), cloogprogram.getCPtr(arg1), cloogoptions.getCPtr(arg2));
  }

  public static void cloog_program_dump_cloog(SWIGTYPE_p_FILE arg0, cloogprogram arg1) {
    CLooGJNI.cloog_program_dump_cloog(SWIGTYPE_p_FILE.getCPtr(arg0), cloogprogram.getCPtr(arg1));
  }

  public static void cloog_program_free(cloogprogram arg0) {
    CLooGJNI.cloog_program_free(cloogprogram.getCPtr(arg0));
  }

  public static cloogprogram cloog_program_read(SWIGTYPE_p_FILE arg0, cloogoptions arg1) {
    long cPtr = CLooGJNI.cloog_program_read(SWIGTYPE_p_FILE.getCPtr(arg0), cloogoptions.getCPtr(arg1));
    return (cPtr == 0) ? null : new cloogprogram(cPtr, false);
  }

  public static cloogprogram cloog_program_malloc() {
    long cPtr = CLooGJNI.cloog_program_malloc();
    return (cPtr == 0) ? null : new cloogprogram(cPtr, false);
  }

  public static cloogprogram cloog_program_generate(cloogprogram arg0, cloogoptions arg1) {
    long cPtr = CLooGJNI.cloog_program_generate(cloogprogram.getCPtr(arg0), cloogoptions.getCPtr(arg1));
    return (cPtr == 0) ? null : new cloogprogram(cPtr, false);
  }

  public static void cloog_program_block(cloogprogram arg0, cloogdomainlist arg1) {
    CLooGJNI.cloog_program_block(cloogprogram.getCPtr(arg0), cloogdomainlist.getCPtr(arg1));
  }

  public static void cloog_program_extract_scalars(cloogprogram program, cloogdomainlist arg1) {
    CLooGJNI.cloog_program_extract_scalars(cloogprogram.getCPtr(program), cloogdomainlist.getCPtr(arg1));
  }

  public static void cloog_program_scatter(cloogprogram arg0, cloogdomainlist arg1) {
    CLooGJNI.cloog_program_scatter(cloogprogram.getCPtr(arg0), cloogdomainlist.getCPtr(arg1));
  }

  public static String pprint_line(SWIGTYPE_p_Matrix arg0, SWIGTYPE_p_Matrix arg1, int arg2, int arg3, clooginfos arg4) {
    return CLooGJNI.pprint_line(SWIGTYPE_p_Matrix.getCPtr(arg0), SWIGTYPE_p_Matrix.getCPtr(arg1), arg2, arg3, clooginfos.getCPtr(arg4));
  }

  public static String pprint_minmax(SWIGTYPE_p_Matrix arg0, SWIGTYPE_p_Matrix arg1, int arg2, int arg3, int arg4, clooginfos arg5) {
    return CLooGJNI.pprint_minmax(SWIGTYPE_p_Matrix.getCPtr(arg0), SWIGTYPE_p_Matrix.getCPtr(arg1), arg2, arg3, arg4, clooginfos.getCPtr(arg5));
  }

  public static void pprint(SWIGTYPE_p_FILE arg0, cloogloop arg1, SWIGTYPE_p_Matrix arg2, int arg3, int arg4, int arg5, clooginfos arg6) {
    CLooGJNI.pprint(SWIGTYPE_p_FILE.getCPtr(arg0), cloogloop.getCPtr(arg1), SWIGTYPE_p_Matrix.getCPtr(arg2), arg3, arg4, arg5, clooginfos.getCPtr(arg6));
  }

}
