/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cloog;

public class cloogoptions {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected cloogoptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cloogoptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      CLooGJNI.delete_cloogoptions(swigCPtr);
    }
    swigCPtr = 0;
  }

  public int getL() {
    return CLooGJNI.cloogoptions_l_get(swigCPtr);
  }

  public int getF() {
    return CLooGJNI.cloogoptions_f_get(swigCPtr);
  }

  public int getStop() {
    return CLooGJNI.cloogoptions_stop_get(swigCPtr);
  }

  public int getShortcode() {
    return CLooGJNI.cloogoptions_shortcode_get(swigCPtr);
  }

  public int getStrides() {
    return CLooGJNI.cloogoptions_strides_get(swigCPtr);
  }

  public int getSh() {
    return CLooGJNI.cloogoptions_sh_get(swigCPtr);
  }

  public int getEsp() {
    return CLooGJNI.cloogoptions_esp_get(swigCPtr);
  }

  public int getCsp() {
    return CLooGJNI.cloogoptions_csp_get(swigCPtr);
  }

  public int getFsp() {
    return CLooGJNI.cloogoptions_fsp_get(swigCPtr);
  }

  public int getOtl() {
    return CLooGJNI.cloogoptions_otl_get(swigCPtr);
  }

  public int getBlock() {
    return CLooGJNI.cloogoptions_block_get(swigCPtr);
  }

  public int getCpp() {
    return CLooGJNI.cloogoptions_cpp_get(swigCPtr);
  }

  public int getCompilable() {
    return CLooGJNI.cloogoptions_compilable_get(swigCPtr);
  }

  public String getName() {
    return CLooGJNI.cloogoptions_name_get(swigCPtr);
  }

  public float getTime() {
    return CLooGJNI.cloogoptions_time_get(swigCPtr);
  }

  public int getLeaks() {
    return CLooGJNI.cloogoptions_leaks_get(swigCPtr);
  }

  public int getNobacktrack() {
    return CLooGJNI.cloogoptions_nobacktrack_get(swigCPtr);
  }

  public int getOverride() {
    return CLooGJNI.cloogoptions_override_get(swigCPtr);
  }

  public int getStructure() {
    return CLooGJNI.cloogoptions_structure_get(swigCPtr);
  }

  public int getNoblocks() {
    return CLooGJNI.cloogoptions_noblocks_get(swigCPtr);
  }

  public int getNoscalars() {
    return CLooGJNI.cloogoptions_noscalars_get(swigCPtr);
  }

  public int getNosimplify() {
    return CLooGJNI.cloogoptions_nosimplify_get(swigCPtr);
  }

  public cloogoptions() {
    this(CLooGJNI.new_cloogoptions(), true);
  }

}
