/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cloog;

public interface CLooGConstants {
  public final static String CLOOG_RELEASE = CLooGJNI.CLOOG_RELEASE_get();
  public final static String CLOOG_VERSION = CLooGJNI.CLOOG_VERSION_get();
  public final static int MAX_NAME = CLooGJNI.MAX_NAME_get();
  public final static char FIRST_PARAMETER = CLooGJNI.FIRST_PARAMETER_get();
  public final static char FIRST_ITERATOR = CLooGJNI.FIRST_ITERATOR_get();
  public final static int MAX_STRING = CLooGJNI.MAX_STRING_get();
  public final static int MEGA = CLooGJNI.MEGA_get();
  public final static int MAX_STRING_VAL = CLooGJNI.MAX_STRING_VAL_get();
  public final static int INDENT_STEP = CLooGJNI.INDENT_STEP_get();
  public final static int ONE_TIME_LOOP = CLooGJNI.ONE_TIME_LOOP_get();
  public final static int EQTYPE_CONSTANT = CLooGJNI.EQTYPE_CONSTANT_get();
  public final static int EQTYPE_PUREITEM = CLooGJNI.EQTYPE_PUREITEM_get();
  public final static int EQTYPE_EXAFFINE = CLooGJNI.EQTYPE_EXAFFINE_get();
  public final static int LANGUAGE_C = CLooGJNI.LANGUAGE_C_get();
  public final static int LANGUAGE_FORTRAN = CLooGJNI.LANGUAGE_FORTRAN_get();
}
