/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cloog;

public class cloogblock {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected cloogblock(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cloogblock obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      CLooGJNI.delete_cloogblock(swigCPtr);
    }
    swigCPtr = 0;
  }

  public cloogstatement getStatement() {
    long cPtr = CLooGJNI.cloogblock_statement_get(swigCPtr);
    return (cPtr == 0) ? null : new cloogstatement(cPtr, false);
  }

  public SWIGTYPE_p_Matrix getScattering() {
    long cPtr = CLooGJNI.cloogblock_scattering_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Matrix(cPtr, false);
  }

  public int getNb_scaldims() {
    return CLooGJNI.cloogblock_nb_scaldims_get(swigCPtr);
  }

  public SWIGTYPE_p_Value getScaldims() {
    long cPtr = CLooGJNI.cloogblock_scaldims_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Value(cPtr, false);
  }

  public int getDepth() {
    return CLooGJNI.cloogblock_depth_get(swigCPtr);
  }

  public int getReferences() {
    return CLooGJNI.cloogblock_references_get(swigCPtr);
  }

  public cloogblock() {
    this(CLooGJNI.new_cloogblock(), true);
  }

}
