/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cloog;

public class cloogprogram {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected cloogprogram(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cloogprogram obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      CLooGJNI.delete_cloogprogram(swigCPtr);
    }
    swigCPtr = 0;
  }

  public char getLanguage() {
    return CLooGJNI.cloogprogram_language_get(swigCPtr);
  }

  public int getNb_scattdims() {
    return CLooGJNI.cloogprogram_nb_scattdims_get(swigCPtr);
  }

  public cloogdomain getContext() {
    long cPtr = CLooGJNI.cloogprogram_context_get(swigCPtr);
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public cloogloop getLoop() {
    long cPtr = CLooGJNI.cloogprogram_loop_get(swigCPtr);
    return (cPtr == 0) ? null : new cloogloop(cPtr, false);
  }

  public cloognames getNames() {
    long cPtr = CLooGJNI.cloogprogram_names_get(swigCPtr);
    return (cPtr == 0) ? null : new cloognames(cPtr, false);
  }

  public cloogblocklist getBlocklist() {
    long cPtr = CLooGJNI.cloogprogram_blocklist_get(swigCPtr);
    return (cPtr == 0) ? null : new cloogblocklist(cPtr, false);
  }

  public SWIGTYPE_p_int getScaldims() {
    long cPtr = CLooGJNI.cloogprogram_scaldims_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public cloogprogram() {
    this(CLooGJNI.new_cloogprogram(), true);
  }

}
