/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cloog;

public class cloogloop {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected cloogloop(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cloogloop obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      CLooGJNI.delete_cloogloop(swigCPtr);
    }
    swigCPtr = 0;
  }

  public cloogdomain getDomain() {
    long cPtr = CLooGJNI.cloogloop_domain_get(swigCPtr);
    return (cPtr == 0) ? null : new cloogdomain(cPtr, false);
  }

  public SWIGTYPE_p_Value getStride() {
    return new SWIGTYPE_p_Value(CLooGJNI.cloogloop_stride_get(swigCPtr), true);
  }

  public cloogblock getBlock() {
    long cPtr = CLooGJNI.cloogloop_block_get(swigCPtr);
    return (cPtr == 0) ? null : new cloogblock(cPtr, false);
  }

  public cloogloop getInner() {
    long cPtr = CLooGJNI.cloogloop_inner_get(swigCPtr);
    return (cPtr == 0) ? null : new cloogloop(cPtr, false);
  }

  public cloogloop getNext() {
    long cPtr = CLooGJNI.cloogloop_next_get(swigCPtr);
    return (cPtr == 0) ? null : new cloogloop(cPtr, false);
  }

  public cloogloop() {
    this(CLooGJNI.new_cloogloop(), true);
  }

}
