/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cloog;

public class cloogstatement {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected cloogstatement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cloogstatement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      CLooGJNI.delete_cloogstatement(swigCPtr);
    }
    swigCPtr = 0;
  }

  public int getNumber() {
    return CLooGJNI.cloogstatement_number_get(swigCPtr);
  }

  public SWIGTYPE_p_void getUsr() {
    long cPtr = CLooGJNI.cloogstatement_usr_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public cloogstatement getNext() {
    long cPtr = CLooGJNI.cloogstatement_next_get(swigCPtr);
    return (cPtr == 0) ? null : new cloogstatement(cPtr, false);
  }

  public cloogstatement() {
    this(CLooGJNI.new_cloogstatement(), true);
  }

}
