/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC)
#   if (__SUNPRO_CC <= 0x560)
#     define SWIGTEMPLATEDISAMBIGUATOR template
#   else
#     define SWIGTEMPLATEDISAMBIGUATOR 
#   endif
# else
#   define SWIGTEMPLATEDISAMBIGUATOR 
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER)
# define _CRT_SECURE_NO_DEPRECATE
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTELC__)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


	#include <stdio.h>
	#include <cloog/cloog.h>


#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_stdin_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  FILE *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (FILE *)stdin;
  *(FILE **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_stdout_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  FILE *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (FILE *)stdout;
  *(FILE **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_stderr_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  FILE *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (FILE *)stderr;
  *(FILE **)&jresult = result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_printf(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jint jresult = 0 ;
  char *arg1 = (char *) 0 ;
  void *arg2 = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (int)printf((char const *)arg1,arg2);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, arg1);
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_fopen(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  FILE *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (FILE *)fopen((char const *)arg1,(char const *)arg2);
  *(FILE **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2);
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_fclose(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  FILE *arg1 = (FILE *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  result = (int)fclose(arg1);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jstring JNICALL Java_cloog_CLooGJNI_CLOOG_1RELEASE_1get(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *) "0.14.1";
  
  if(result) jresult = (*jenv)->NewStringUTF(jenv, result);
  return jresult;
}


JNIEXPORT jstring JNICALL Java_cloog_CLooGJNI_CLOOG_1VERSION_1get(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *) "32";
  
  if(result) jresult = (*jenv)->NewStringUTF(jenv, result);
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1l_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->l);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1f_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->f);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1stop_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->stop);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1shortcode_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->shortcode);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1strides_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->strides);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1sh_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->sh);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1esp_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->esp);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1csp_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->csp);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1fsp_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->fsp);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1otl_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->otl);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1block_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->block);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1cpp_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->cpp);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1compilable_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->compilable);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jstring JNICALL Java_cloog_CLooGJNI_cloogoptions_1name_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (char *) ((arg1)->name);
  if(result) jresult = (*jenv)->NewStringUTF(jenv, result);
  return jresult;
}


JNIEXPORT jfloat JNICALL Java_cloog_CLooGJNI_cloogoptions_1time_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jfloat jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (float) ((arg1)->time);
  jresult = (jfloat)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1leaks_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->leaks);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1nobacktrack_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->nobacktrack);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1override_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->override);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1structure_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->structure);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1noblocks_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->noblocks);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1noscalars_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->noscalars);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogoptions_1nosimplify_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  result = (int) ((arg1)->nosimplify);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_new_1cloogoptions(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct cloogoptions *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct cloogoptions *)(struct cloogoptions *) calloc(1, sizeof(struct cloogoptions));
  *(struct cloogoptions **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_delete_1cloogoptions(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct cloogoptions *arg1 = (struct cloogoptions *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogoptions **)&jarg1; 
  free((char *) arg1);
  
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1options_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  FILE *arg1 = (FILE *) 0 ;
  CloogOptions *arg2 = (CloogOptions *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogOptions **)&jarg2; 
  cloog_options_print(arg1,arg2);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1options_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CloogOptions *arg1 = (CloogOptions *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogOptions **)&jarg1; 
  cloog_options_free(arg1);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1options_1read(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  int arg1 ;
  char **arg2 = (char **) 0 ;
  FILE **arg3 = (FILE **) 0 ;
  FILE **arg4 = (FILE **) 0 ;
  CloogOptions **arg5 = (CloogOptions **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(char ***)&jarg2; 
  arg3 = *(FILE ***)&jarg3; 
  arg4 = *(FILE ***)&jarg4; 
  arg5 = *(CloogOptions ***)&jarg5; 
  cloog_options_read(arg1,arg2,arg3,arg4,arg5);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1options_1malloc(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CloogOptions *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CloogOptions *)cloog_options_malloc();
  *(CloogOptions **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1matrix_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  FILE *arg1 = (FILE *) 0 ;
  Matrix *arg2 = (Matrix *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(Matrix **)&jarg2; 
  cloog_matrix_print(arg1,arg2);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1matrix_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Matrix *arg1 = (Matrix *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Matrix **)&jarg1; 
  cloog_matrix_free(arg1);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1matrix_1alloc(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  unsigned int arg2 ;
  Matrix *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (Matrix *)cloog_matrix_alloc(arg1,arg2);
  *(Matrix **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1matrix_1matrix(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  Matrix *arg1 = (Matrix *) 0 ;
  Matrix *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Matrix **)&jarg1; 
  result = (Matrix *)cloog_matrix_matrix(arg1);
  *(Matrix **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1matrix_1print_1structure(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  FILE *arg1 = (FILE *) 0 ;
  Matrix *arg2 = (Matrix *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(Matrix **)&jarg2; 
  arg3 = (int)jarg3; 
  cloog_matrix_print_structure(arg1,arg2,arg3);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1matrix_1read(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  FILE *arg1 = (FILE *) 0 ;
  Matrix *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  result = (Matrix *)cloog_matrix_read(arg1);
  *(Matrix **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1matrix_1normalize(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  Matrix *arg1 = (Matrix *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Matrix **)&jarg1; 
  arg2 = (int)jarg2; 
  cloog_matrix_normalize(arg1,arg2);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1matrix_1equality_1update(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
  Matrix *arg1 = (Matrix *) 0 ;
  int arg2 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Matrix **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  cloog_matrix_equality_update(arg1,arg2,arg3);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1matrix_1copy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  Matrix *arg1 = (Matrix *) 0 ;
  Matrix *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Matrix **)&jarg1; 
  result = (Matrix *)cloog_matrix_copy(arg1);
  *(Matrix **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1matrix_1vector_1copy(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  Value *arg1 = (Value *) 0 ;
  int arg2 ;
  Value *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Value **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (Value *)cloog_matrix_vector_copy(arg1,arg2);
  *(Value **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1matrix_1vector_1simplify(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4, jint jarg5) {
  jlong jresult = 0 ;
  Value *arg1 = (Value *) 0 ;
  Matrix *arg2 = (Matrix *) 0 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  Value *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Value **)&jarg1; 
  arg2 = *(Matrix **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (int)jarg5; 
  result = (Value *)cloog_matrix_vector_simplify(arg1,arg2,arg3,arg4,arg5);
  *(Value **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1matrix_1simplify(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4) {
  jlong jresult = 0 ;
  Matrix *arg1 = (Matrix *) 0 ;
  Matrix *arg2 = (Matrix *) 0 ;
  int arg3 ;
  int arg4 ;
  Matrix *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Matrix **)&jarg1; 
  arg2 = *(Matrix **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (Matrix *)cloog_matrix_simplify(arg1,arg2,arg3,arg4);
  *(Matrix **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1matrix_1vector_1free(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  Value *arg1 = (Value *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Value **)&jarg1; 
  arg2 = (int)jarg2; 
  cloog_matrix_vector_free(arg1,arg2);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogdomain_1polyhedron_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogdomain *arg1 = (struct cloogdomain *) 0 ;
  Polyhedron *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogdomain **)&jarg1; 
  result = (Polyhedron *) ((arg1)->polyhedron);
  *(Polyhedron **)&jresult = result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogdomain_1references_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogdomain *arg1 = (struct cloogdomain *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogdomain **)&jarg1; 
  result = (int) ((arg1)->references);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_new_1cloogdomain(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct cloogdomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct cloogdomain *)(struct cloogdomain *) calloc(1, sizeof(struct cloogdomain));
  *(struct cloogdomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_delete_1cloogdomain(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct cloogdomain *arg1 = (struct cloogdomain *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogdomain **)&jarg1; 
  free((char *) arg1);
  
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogdomainlist_1domain_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogdomainlist *arg1 = (struct cloogdomainlist *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogdomainlist **)&jarg1; 
  result = (CloogDomain *) ((arg1)->domain);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogdomainlist_1next_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogdomainlist *arg1 = (struct cloogdomainlist *) 0 ;
  struct cloogdomainlist *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogdomainlist **)&jarg1; 
  result = (struct cloogdomainlist *) ((arg1)->next);
  *(struct cloogdomainlist **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_new_1cloogdomainlist(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct cloogdomainlist *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct cloogdomainlist *)(struct cloogdomainlist *) calloc(1, sizeof(struct cloogdomainlist));
  *(struct cloogdomainlist **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_delete_1cloogdomainlist(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct cloogdomainlist *arg1 = (struct cloogdomainlist *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogdomainlist **)&jarg1; 
  free((char *) arg1);
  
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1value_1leak_1up(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  cloog_value_leak_up();
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1value_1leak_1down(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  cloog_value_leak_down();
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1matrix2domain(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  Matrix *arg1 = (Matrix *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Matrix **)&jarg1; 
  result = (CloogDomain *)cloog_domain_matrix2domain(arg1);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1domain2matrix(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  Matrix *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  result = (Matrix *)cloog_domain_domain2matrix(arg1);
  *(Matrix **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1domain_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  FILE *arg1 = (FILE *) 0 ;
  CloogDomain *arg2 = (CloogDomain *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogDomain **)&jarg2; 
  cloog_domain_print(arg1,arg2);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1polyhedron_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  FILE *arg1 = (FILE *) 0 ;
  Polyhedron *arg2 = (Polyhedron *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(Polyhedron **)&jarg2; 
  cloog_polyhedron_print(arg1,arg2);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1domain_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  cloog_domain_free(arg1);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1copy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  result = (CloogDomain *)cloog_domain_copy(arg1);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1image(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  Matrix *arg2 = (Matrix *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = *(Matrix **)&jarg2; 
  result = (CloogDomain *)cloog_domain_image(arg1,arg2);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1preimage(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  Matrix *arg2 = (Matrix *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = *(Matrix **)&jarg2; 
  result = (CloogDomain *)cloog_domain_preimage(arg1,arg2);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1convex(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  result = (CloogDomain *)cloog_domain_convex(arg1);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1simple_1convex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  int arg2 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (CloogDomain *)cloog_domain_simple_convex(arg1,arg2);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1simplify(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  CloogDomain *arg2 = (CloogDomain *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = *(CloogDomain **)&jarg2; 
  result = (CloogDomain *)cloog_domain_simplify(arg1,arg2);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1union(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  CloogDomain *arg2 = (CloogDomain *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = *(CloogDomain **)&jarg2; 
  result = (CloogDomain *)cloog_domain_union(arg1,arg2);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1disjoint(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  result = (CloogDomain *)cloog_domain_disjoint(arg1);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1intersection(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  CloogDomain *arg2 = (CloogDomain *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = *(CloogDomain **)&jarg2; 
  result = (CloogDomain *)cloog_domain_intersection(arg1,arg2);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1difference(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  CloogDomain *arg2 = (CloogDomain *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = *(CloogDomain **)&jarg2; 
  result = (CloogDomain *)cloog_domain_difference(arg1,arg2);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloog_1domain_1includes(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  CloogDomain *arg2 = (CloogDomain *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = *(CloogDomain **)&jarg2; 
  result = (int)cloog_domain_includes(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1addconstraints(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  CloogDomain *arg2 = (CloogDomain *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = *(CloogDomain **)&jarg2; 
  result = (CloogDomain *)cloog_domain_addconstraints(arg1,arg2);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1domain_1sort(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  Polyhedron **arg1 = (Polyhedron **) 0 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  unsigned int arg4 ;
  int *arg5 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Polyhedron ***)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  arg3 = (unsigned int)jarg3; 
  arg4 = (unsigned int)jarg4; 
  arg5 = *(int **)&jarg5; 
  cloog_domain_sort(arg1,arg2,arg3,arg4,arg5);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1empty(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (CloogDomain *)cloog_domain_empty(arg1);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1domain_1print_1structure(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  FILE *arg1 = (FILE *) 0 ;
  CloogDomain *arg2 = (CloogDomain *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogDomain **)&jarg2; 
  arg3 = (int)jarg3; 
  cloog_domain_print_structure(arg1,arg2,arg3);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1domain_1list_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  FILE *arg1 = (FILE *) 0 ;
  CloogDomainList *arg2 = (CloogDomainList *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogDomainList **)&jarg2; 
  cloog_domain_list_print(arg1,arg2);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1domain_1list_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CloogDomainList *arg1 = (CloogDomainList *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomainList **)&jarg1; 
  cloog_domain_list_free(arg1);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1read(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  FILE *arg1 = (FILE *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  result = (CloogDomain *)cloog_domain_read(arg1);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1union_1read(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  FILE *arg1 = (FILE *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  result = (CloogDomain *)cloog_domain_union_read(arg1);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1list_1read(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  FILE *arg1 = (FILE *) 0 ;
  CloogDomainList *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  result = (CloogDomainList *)cloog_domain_list_read(arg1);
  *(CloogDomainList **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1malloc(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CloogDomain *)cloog_domain_malloc();
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1alloc(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  Polyhedron *arg1 = (Polyhedron *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Polyhedron **)&jarg1; 
  result = (CloogDomain *)cloog_domain_alloc(arg1);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1compact(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  //result = (CloogDomain *)cloog_domain_compact(arg1);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloog_1domain_1isempty(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  result = (int)cloog_domain_isempty(arg1);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloog_1domain_1universe(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  result = (int)cloog_domain_universe(arg1);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1project(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  int arg2 ;
  int arg3 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (CloogDomain *)cloog_domain_project(arg1,arg2,arg3);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1bounds(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  int arg2 ;
  int arg3 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (CloogDomain *)cloog_domain_bounds(arg1,arg2,arg3);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1extend(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  int arg2 ;
  int arg3 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (CloogDomain *)cloog_domain_extend(arg1,arg2,arg3);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloog_1domain_1never_1integral(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  result = (int)cloog_domain_never_integral(arg1);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1domain_1stride(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jlong jarg4, jlong jarg5) {
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  int arg2 ;
  int arg3 ;
  Value *arg4 = (Value *) 0 ;
  Value *arg5 = (Value *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(Value **)&jarg4; 
  arg5 = *(Value **)&jarg5; 
  cloog_domain_stride(arg1,arg2,arg3,arg4,arg5);
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloog_1domain_1integral_1lowerbound(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  jint jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  int arg2 ;
  Value *arg3 = (Value *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Value **)&jarg3; 
  result = (int)cloog_domain_integral_lowerbound(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1domain_1lowerbound_1update(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  int arg2 ;
  Value arg3 ;
  Value *argp3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = (int)jarg2; 
  argp3 = *(Value **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null Value");
    return ;
  }
  arg3 = *argp3; 
  cloog_domain_lowerbound_update(arg1,arg2,arg3);
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloog_1domain_1lazy_1disjoint(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  CloogDomain *arg2 = (CloogDomain *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = *(CloogDomain **)&jarg2; 
  result = (int)cloog_domain_lazy_disjoint(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloog_1domain_1lazy_1equal(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  CloogDomain *arg2 = (CloogDomain *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = *(CloogDomain **)&jarg2; 
  result = (int)cloog_domain_lazy_equal(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloog_1domain_1lazy_1block(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jint jarg4) {
  jint jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  CloogDomain *arg2 = (CloogDomain *) 0 ;
  CloogDomainList *arg3 = (CloogDomainList *) 0 ;
  int arg4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = *(CloogDomain **)&jarg2; 
  arg3 = *(CloogDomainList **)&jarg3; 
  arg4 = (int)jarg4; 
  result = (int)cloog_domain_lazy_block(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloog_1domain_1lazy_1isscalar(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (int)cloog_domain_lazy_isscalar(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloog_1domain_1list_1lazy_1same(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  CloogDomainList *arg1 = (CloogDomainList *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomainList **)&jarg1; 
  result = (int)cloog_domain_list_lazy_same(arg1);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1domain_1scalar(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  int arg2 ;
  Value *arg3 = (Value *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Value **)&jarg3; 
  cloog_domain_scalar(arg1,arg2,arg3);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1grow(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  int arg2 ;
  int arg3 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (CloogDomain *)cloog_domain_grow(arg1,arg2,arg3);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1cut_1first(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  result = (CloogDomain *)cloog_domain_cut_first(arg1);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1domain_1erase_1dimension(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  int arg2 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (CloogDomain *)cloog_domain_erase_dimension(arg1,arg2);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1domain_1reverse(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CloogDomain *arg1 = (CloogDomain *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogDomain **)&jarg1; 
  cloog_domain_reverse(arg1);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1domain_1line_1update(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4) {
  Polyhedron *arg1 = (Polyhedron *) 0 ;
  Matrix *arg2 = (Matrix *) 0 ;
  int arg3 ;
  int arg4 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Polyhedron **)&jarg1; 
  arg2 = *(Matrix **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  //cloog_domain_line_update(arg1,arg2,arg3,arg4);
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogstatement_1number_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogstatement *arg1 = (struct cloogstatement *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogstatement **)&jarg1; 
  result = (int) ((arg1)->number);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogstatement_1usr_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogstatement *arg1 = (struct cloogstatement *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogstatement **)&jarg1; 
  result = (void *) ((arg1)->usr);
  *(void **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogstatement_1next_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogstatement *arg1 = (struct cloogstatement *) 0 ;
  struct cloogstatement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogstatement **)&jarg1; 
  result = (struct cloogstatement *) ((arg1)->next);
  *(struct cloogstatement **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_new_1cloogstatement(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct cloogstatement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct cloogstatement *)(struct cloogstatement *) calloc(1, sizeof(struct cloogstatement));
  *(struct cloogstatement **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_delete_1cloogstatement(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct cloogstatement *arg1 = (struct cloogstatement *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogstatement **)&jarg1; 
  free((char *) arg1);
  
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1statement_1print_1structure(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  FILE *arg1 = (FILE *) 0 ;
  CloogStatement *arg2 = (CloogStatement *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogStatement **)&jarg2; 
  arg3 = (int)jarg3; 
  cloog_statement_print_structure(arg1,arg2,arg3);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1statement_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  FILE *arg1 = (FILE *) 0 ;
  CloogStatement *arg2 = (CloogStatement *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogStatement **)&jarg2; 
  cloog_statement_print(arg1,arg2);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1statement_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CloogStatement *arg1 = (CloogStatement *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogStatement **)&jarg1; 
  cloog_statement_free(arg1);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1statement_1malloc(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CloogStatement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CloogStatement *)cloog_statement_malloc();
  *(CloogStatement **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1statement_1alloc(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  CloogStatement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (CloogStatement *)cloog_statement_alloc(arg1);
  *(CloogStatement **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1statement_1copy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CloogStatement *arg1 = (CloogStatement *) 0 ;
  CloogStatement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogStatement **)&jarg1; 
  result = (CloogStatement *)cloog_statement_copy(arg1);
  *(CloogStatement **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1statement_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  CloogStatement **arg1 = (CloogStatement **) 0 ;
  CloogStatement **arg2 = (CloogStatement **) 0 ;
  CloogStatement *arg3 = (CloogStatement *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogStatement ***)&jarg1; 
  arg2 = *(CloogStatement ***)&jarg2; 
  arg3 = *(CloogStatement **)&jarg3; 
  cloog_statement_add(arg1,arg2,arg3);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogblock_1statement_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogblock *arg1 = (struct cloogblock *) 0 ;
  CloogStatement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogblock **)&jarg1; 
  result = (CloogStatement *) ((arg1)->statement);
  *(CloogStatement **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogblock_1scattering_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogblock *arg1 = (struct cloogblock *) 0 ;
  Matrix *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogblock **)&jarg1; 
  result = (Matrix *) ((arg1)->scattering);
  *(Matrix **)&jresult = result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogblock_1nb_1scaldims_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogblock *arg1 = (struct cloogblock *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogblock **)&jarg1; 
  result = (int) ((arg1)->nb_scaldims);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogblock_1scaldims_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogblock *arg1 = (struct cloogblock *) 0 ;
  Value *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogblock **)&jarg1; 
  result = (Value *) ((arg1)->scaldims);
  *(Value **)&jresult = result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogblock_1depth_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogblock *arg1 = (struct cloogblock *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogblock **)&jarg1; 
  result = (int) ((arg1)->depth);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogblock_1references_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogblock *arg1 = (struct cloogblock *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogblock **)&jarg1; 
  result = (int) ((arg1)->references);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_new_1cloogblock(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct cloogblock *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct cloogblock *)(struct cloogblock *) calloc(1, sizeof(struct cloogblock));
  *(struct cloogblock **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_delete_1cloogblock(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct cloogblock *arg1 = (struct cloogblock *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogblock **)&jarg1; 
  free((char *) arg1);
  
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogblocklist_1block_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogblocklist *arg1 = (struct cloogblocklist *) 0 ;
  CloogBlock *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogblocklist **)&jarg1; 
  result = (CloogBlock *) ((arg1)->block);
  *(CloogBlock **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogblocklist_1next_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogblocklist *arg1 = (struct cloogblocklist *) 0 ;
  struct cloogblocklist *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogblocklist **)&jarg1; 
  result = (struct cloogblocklist *) ((arg1)->next);
  *(struct cloogblocklist **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_new_1cloogblocklist(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct cloogblocklist *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct cloogblocklist *)(struct cloogblocklist *) calloc(1, sizeof(struct cloogblocklist));
  *(struct cloogblocklist **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_delete_1cloogblocklist(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct cloogblocklist *arg1 = (struct cloogblocklist *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogblocklist **)&jarg1; 
  free((char *) arg1);
  
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1block_1print_1structure(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  FILE *arg1 = (FILE *) 0 ;
  CloogBlock *arg2 = (CloogBlock *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogBlock **)&jarg2; 
  arg3 = (int)jarg3; 
  cloog_block_print_structure(arg1,arg2,arg3);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1block_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  FILE *arg1 = (FILE *) 0 ;
  CloogBlock *arg2 = (CloogBlock *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogBlock **)&jarg2; 
  cloog_block_print(arg1,arg2);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1block_1list_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  FILE *arg1 = (FILE *) 0 ;
  CloogBlockList *arg2 = (CloogBlockList *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogBlockList **)&jarg2; 
  cloog_block_list_print(arg1,arg2);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1block_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CloogBlock *arg1 = (CloogBlock *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogBlock **)&jarg1; 
  cloog_block_free(arg1);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1block_1list_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CloogBlockList *arg1 = (CloogBlockList *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogBlockList **)&jarg1; 
  cloog_block_list_free(arg1);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1block_1malloc(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CloogBlock *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CloogBlock *)cloog_block_malloc();
  *(CloogBlock **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1block_1alloc(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jint jarg5) {
  jlong jresult = 0 ;
  CloogStatement *arg1 = (CloogStatement *) 0 ;
  Matrix *arg2 = (Matrix *) 0 ;
  int arg3 ;
  Value *arg4 = (Value *) 0 ;
  int arg5 ;
  CloogBlock *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogStatement **)&jarg1; 
  arg2 = *(Matrix **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(Value **)&jarg4; 
  arg5 = (int)jarg5; 
  result = (CloogBlock *)cloog_block_alloc(arg1,arg2,arg3,arg4,arg5);
  *(CloogBlock **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1block_1list_1malloc(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CloogBlockList *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CloogBlockList *)cloog_block_list_malloc();
  *(CloogBlockList **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1block_1list_1alloc(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CloogBlock *arg1 = (CloogBlock *) 0 ;
  CloogBlockList *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogBlock **)&jarg1; 
  result = (CloogBlockList *)cloog_block_list_alloc(arg1);
  *(CloogBlockList **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1block_1copy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CloogBlock *arg1 = (CloogBlock *) 0 ;
  CloogBlock *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogBlock **)&jarg1; 
  result = (CloogBlock *)cloog_block_copy(arg1);
  *(CloogBlock **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1block_1merge(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  CloogBlock *arg1 = (CloogBlock *) 0 ;
  CloogBlock *arg2 = (CloogBlock *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogBlock **)&jarg1; 
  arg2 = *(CloogBlock **)&jarg2; 
  cloog_block_merge(arg1,arg2);
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_MAX_1NAME_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 50;
  
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jchar JNICALL Java_cloog_CLooGJNI_FIRST_1PARAMETER_1get(JNIEnv *jenv, jclass jcls) {
  jchar jresult = 0 ;
  char result;
  
  (void)jenv;
  (void)jcls;
  result = (char) 'M';
  
  jresult = (jchar)result; 
  return jresult;
}


JNIEXPORT jchar JNICALL Java_cloog_CLooGJNI_FIRST_1ITERATOR_1get(JNIEnv *jenv, jclass jcls) {
  jchar jresult = 0 ;
  char result;
  
  (void)jenv;
  (void)jcls;
  result = (char) 'i';
  
  jresult = (jchar)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloognames_1nb_1scalars_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloognames *arg1 = (struct cloognames *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloognames **)&jarg1; 
  result = (int) ((arg1)->nb_scalars);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloognames_1nb_1scattering_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloognames *arg1 = (struct cloognames *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloognames **)&jarg1; 
  result = (int) ((arg1)->nb_scattering);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloognames_1nb_1iterators_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloognames *arg1 = (struct cloognames *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloognames **)&jarg1; 
  result = (int) ((arg1)->nb_iterators);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloognames_1nb_1parameters_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloognames *arg1 = (struct cloognames *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloognames **)&jarg1; 
  result = (int) ((arg1)->nb_parameters);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloognames_1scalars_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloognames *arg1 = (struct cloognames *) 0 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloognames **)&jarg1; 
  result = (char **) ((arg1)->scalars);
  *(char ***)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloognames_1scattering_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloognames *arg1 = (struct cloognames *) 0 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloognames **)&jarg1; 
  result = (char **) ((arg1)->scattering);
  *(char ***)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloognames_1iterators_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloognames *arg1 = (struct cloognames *) 0 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloognames **)&jarg1; 
  result = (char **) ((arg1)->iterators);
  *(char ***)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloognames_1parameters_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloognames *arg1 = (struct cloognames *) 0 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloognames **)&jarg1; 
  result = (char **) ((arg1)->parameters);
  *(char ***)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_new_1cloognames(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct cloognames *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct cloognames *)(struct cloognames *) calloc(1, sizeof(struct cloognames));
  *(struct cloognames **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_delete_1cloognames(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct cloognames *arg1 = (struct cloognames *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloognames **)&jarg1; 
  free((char *) arg1);
  
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1names_1print_1structure(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  FILE *arg1 = (FILE *) 0 ;
  CloogNames *arg2 = (CloogNames *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogNames **)&jarg2; 
  arg3 = (int)jarg3; 
  cloog_names_print_structure(arg1,arg2,arg3);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1names_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  FILE *arg1 = (FILE *) 0 ;
  CloogNames *arg2 = (CloogNames *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogNames **)&jarg2; 
  cloog_names_print(arg1,arg2);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1names_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CloogNames *arg1 = (CloogNames *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogNames **)&jarg1; 
  cloog_names_free(arg1);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1names_1read_1strings(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jstring jarg3, jchar jarg4) {
  jlong jresult = 0 ;
  FILE *arg1 = (FILE *) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  char arg4 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (char)jarg4; 
  result = (char **)cloog_names_read_strings(arg1,arg2,arg3,arg4);
  *(char ***)&jresult = result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, arg3);
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1names_1malloc(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CloogNames *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CloogNames *)cloog_names_malloc();
  *(CloogNames **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1names_1alloc(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3, jint jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  char **arg5 = (char **) 0 ;
  char **arg6 = (char **) 0 ;
  char **arg7 = (char **) 0 ;
  char **arg8 = (char **) 0 ;
  CloogNames *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = *(char ***)&jarg5; 
  arg6 = *(char ***)&jarg6; 
  arg7 = *(char ***)&jarg7; 
  arg8 = *(char ***)&jarg8; 
  result = (CloogNames *)cloog_names_alloc(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  *(CloogNames **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1names_1generate_1items(JNIEnv *jenv, jclass jcls, jint jarg1, jstring jarg2, jchar jarg3) {
  jlong jresult = 0 ;
  int arg1 ;
  char *arg2 = (char *) 0 ;
  char arg3 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (char)jarg3; 
  result = (char **)cloog_names_generate_items(arg1,arg2,arg3);
  *(char ***)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2);
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1names_1generate(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3, jint jarg4, jchar jarg5, jchar jarg6, jchar jarg7, jchar jarg8) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  char arg5 ;
  char arg6 ;
  char arg7 ;
  char arg8 ;
  CloogNames *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (char)jarg5; 
  arg6 = (char)jarg6; 
  arg7 = (char)jarg7; 
  arg8 = (char)jarg8; 
  result = (CloogNames *)cloog_names_generate(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  *(CloogNames **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1names_1scalarize(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  CloogNames *arg1 = (CloogNames *) 0 ;
  int arg2 ;
  int *arg3 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogNames **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(int **)&jarg3; 
  cloog_names_scalarize(arg1,arg2,arg3);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogloop_1domain_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogloop *arg1 = (struct cloogloop *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogloop **)&jarg1; 
  result = (CloogDomain *) ((arg1)->domain);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogloop_1stride_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogloop *arg1 = (struct cloogloop *) 0 ;
  Value result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogloop **)&jarg1; 
  result =  ((arg1)->stride);
  {
    Value * resultptr = (Value *) malloc(sizeof(Value));
    memmove(resultptr, &result, sizeof(Value));
    *(Value **)&jresult = resultptr;
  }
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogloop_1block_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogloop *arg1 = (struct cloogloop *) 0 ;
  CloogBlock *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogloop **)&jarg1; 
  result = (CloogBlock *) ((arg1)->block);
  *(CloogBlock **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogloop_1inner_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogloop *arg1 = (struct cloogloop *) 0 ;
  struct cloogloop *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogloop **)&jarg1; 
  result = (struct cloogloop *) ((arg1)->inner);
  *(struct cloogloop **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogloop_1next_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogloop *arg1 = (struct cloogloop *) 0 ;
  struct cloogloop *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogloop **)&jarg1; 
  result = (struct cloogloop *) ((arg1)->next);
  *(struct cloogloop **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_new_1cloogloop(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct cloogloop *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct cloogloop *)(struct cloogloop *) calloc(1, sizeof(struct cloogloop));
  *(struct cloogloop **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_delete_1cloogloop(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct cloogloop *arg1 = (struct cloogloop *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogloop **)&jarg1; 
  free((char *) arg1);
  
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1loop_1print_1structure(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  FILE *arg1 = (FILE *) 0 ;
  CloogLoop *arg2 = (CloogLoop *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogLoop **)&jarg2; 
  arg3 = (int)jarg3; 
  cloog_loop_print_structure(arg1,arg2,arg3);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1loop_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  FILE *arg1 = (FILE *) 0 ;
  CloogLoop *arg2 = (CloogLoop *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogLoop **)&jarg2; 
  cloog_loop_print(arg1,arg2);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1loop_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CloogLoop *arg1 = (CloogLoop *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogLoop **)&jarg1; 
  cloog_loop_free(arg1);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1loop_1read(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
  jlong jresult = 0 ;
  FILE *arg1 = (FILE *) 0 ;
  int arg2 ;
  int arg3 ;
  CloogLoop *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (CloogLoop *)cloog_loop_read(arg1,arg2,arg3);
  *(CloogLoop **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1loop_1malloc(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CloogLoop *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CloogLoop *)cloog_loop_malloc();
  *(CloogLoop **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1loop_1generate(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4, jlong jarg5, jint jarg6, jint jarg7, jlong jarg8) {
  jlong jresult = 0 ;
  CloogLoop *arg1 = (CloogLoop *) 0 ;
  CloogDomain *arg2 = (CloogDomain *) 0 ;
  int arg3 ;
  int arg4 ;
  int *arg5 = (int *) 0 ;
  int arg6 ;
  int arg7 ;
  CloogOptions *arg8 = (CloogOptions *) 0 ;
  CloogLoop *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogLoop **)&jarg1; 
  arg2 = *(CloogDomain **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = *(int **)&jarg5; 
  arg6 = (int)jarg6; 
  arg7 = (int)jarg7; 
  arg8 = *(CloogOptions **)&jarg8; 
  result = (CloogLoop *)cloog_loop_generate(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  *(CloogLoop **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1loop_1simplify(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4) {
  jlong jresult = 0 ;
  CloogLoop *arg1 = (CloogLoop *) 0 ;
  CloogDomain *arg2 = (CloogDomain *) 0 ;
  int arg3 ;
  int arg4 ;
  CloogLoop *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogLoop **)&jarg1; 
  arg2 = *(CloogDomain **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (CloogLoop *)cloog_loop_simplify(arg1,arg2,arg3,arg4);
  *(CloogLoop **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1loop_1scatter(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  CloogLoop *arg1 = (CloogLoop *) 0 ;
  CloogDomain *arg2 = (CloogDomain *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogLoop **)&jarg1; 
  arg2 = *(CloogDomain **)&jarg2; 
  cloog_loop_scatter(arg1,arg2);
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_MAX_1STRING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 1024;
  
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_MEGA_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 1000000;
  
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jchar JNICALL Java_cloog_CLooGJNI_cloogprogram_1language_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jchar jresult = 0 ;
  struct cloogprogram *arg1 = (struct cloogprogram *) 0 ;
  char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogprogram **)&jarg1; 
  result = (char) ((arg1)->language);
  jresult = (jchar)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_cloogprogram_1nb_1scattdims_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct cloogprogram *arg1 = (struct cloogprogram *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogprogram **)&jarg1; 
  result = (int) ((arg1)->nb_scattdims);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogprogram_1context_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogprogram *arg1 = (struct cloogprogram *) 0 ;
  CloogDomain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogprogram **)&jarg1; 
  result = (CloogDomain *) ((arg1)->context);
  *(CloogDomain **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogprogram_1loop_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogprogram *arg1 = (struct cloogprogram *) 0 ;
  CloogLoop *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogprogram **)&jarg1; 
  result = (CloogLoop *) ((arg1)->loop);
  *(CloogLoop **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogprogram_1names_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogprogram *arg1 = (struct cloogprogram *) 0 ;
  CloogNames *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogprogram **)&jarg1; 
  result = (CloogNames *) ((arg1)->names);
  *(CloogNames **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogprogram_1blocklist_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogprogram *arg1 = (struct cloogprogram *) 0 ;
  CloogBlockList *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogprogram **)&jarg1; 
  result = (CloogBlockList *) ((arg1)->blocklist);
  *(CloogBlockList **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloogprogram_1scaldims_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct cloogprogram *arg1 = (struct cloogprogram *) 0 ;
  int *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogprogram **)&jarg1; 
  result = (int *) ((arg1)->scaldims);
  *(int **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_new_1cloogprogram(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct cloogprogram *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct cloogprogram *)(struct cloogprogram *) calloc(1, sizeof(struct cloogprogram));
  *(struct cloogprogram **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_delete_1cloogprogram(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct cloogprogram *arg1 = (struct cloogprogram *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct cloogprogram **)&jarg1; 
  free((char *) arg1);
  
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1program_1print_1structure(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  FILE *arg1 = (FILE *) 0 ;
  CloogProgram *arg2 = (CloogProgram *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogProgram **)&jarg2; 
  arg3 = (int)jarg3; 
  cloog_program_print_structure(arg1,arg2,arg3);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1program_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  FILE *arg1 = (FILE *) 0 ;
  CloogProgram *arg2 = (CloogProgram *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogProgram **)&jarg2; 
  cloog_program_print(arg1,arg2);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1program_1pprint(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  FILE *arg1 = (FILE *) 0 ;
  CloogProgram *arg2 = (CloogProgram *) 0 ;
  CloogOptions *arg3 = (CloogOptions *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogProgram **)&jarg2; 
  arg3 = *(CloogOptions **)&jarg3; 
  cloog_program_pprint(arg1,arg2,arg3);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1program_1dump_1cloog(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  FILE *arg1 = (FILE *) 0 ;
  CloogProgram *arg2 = (CloogProgram *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogProgram **)&jarg2; 
  cloog_program_dump_cloog(arg1,arg2);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1program_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CloogProgram *arg1 = (CloogProgram *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogProgram **)&jarg1; 
  cloog_program_free(arg1);
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1program_1read(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  FILE *arg1 = (FILE *) 0 ;
  CloogOptions *arg2 = (CloogOptions *) 0 ;
  CloogProgram *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogOptions **)&jarg2; 
  result = (CloogProgram *)cloog_program_read(arg1,arg2);
  *(CloogProgram **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1program_1malloc(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CloogProgram *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CloogProgram *)cloog_program_malloc();
  *(CloogProgram **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_cloog_1program_1generate(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CloogProgram *arg1 = (CloogProgram *) 0 ;
  CloogOptions *arg2 = (CloogOptions *) 0 ;
  CloogProgram *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogProgram **)&jarg1; 
  arg2 = *(CloogOptions **)&jarg2; 
  result = (CloogProgram *)cloog_program_generate(arg1,arg2);
  *(CloogProgram **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1program_1block(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  CloogProgram *arg1 = (CloogProgram *) 0 ;
  CloogDomainList *arg2 = (CloogDomainList *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogProgram **)&jarg1; 
  arg2 = *(CloogDomainList **)&jarg2; 
  cloog_program_block(arg1,arg2);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1program_1extract_1scalars(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  CloogProgram *arg1 = (CloogProgram *) 0 ;
  CloogDomainList *arg2 = (CloogDomainList *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogProgram **)&jarg1; 
  arg2 = *(CloogDomainList **)&jarg2; 
  cloog_program_extract_scalars(arg1,arg2);
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_cloog_1program_1scatter(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  CloogProgram *arg1 = (CloogProgram *) 0 ;
  CloogDomainList *arg2 = (CloogDomainList *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CloogProgram **)&jarg1; 
  arg2 = *(CloogDomainList **)&jarg2; 
  cloog_program_scatter(arg1,arg2);
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_MAX_1STRING_1VAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 32;
  
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_INDENT_1STEP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 2;
  
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_ONE_1TIME_1LOOP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) -1;
  
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_EQTYPE_1CONSTANT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 1;
  
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_EQTYPE_1PUREITEM_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 2;
  
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_EQTYPE_1EXAFFINE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 3;
  
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_LANGUAGE_1C_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 0;
  
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_LANGUAGE_1FORTRAN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 1;
  
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_clooginfos_1stride_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct clooginfos *arg1 = (struct clooginfos *) 0 ;
  Value *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct clooginfos **)&jarg1; 
  result = (Value *) ((arg1)->stride);
  *(Value **)&jresult = result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_clooginfos_1language_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct clooginfos *arg1 = (struct clooginfos *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct clooginfos **)&jarg1; 
  result = (int) ((arg1)->language);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jint JNICALL Java_cloog_CLooGJNI_clooginfos_1nb_1scattdims_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  struct clooginfos *arg1 = (struct clooginfos *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct clooginfos **)&jarg1; 
  result = (int) ((arg1)->nb_scattdims);
  jresult = (jint)result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_clooginfos_1scaldims_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct clooginfos *arg1 = (struct clooginfos *) 0 ;
  int *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct clooginfos **)&jarg1; 
  result = (int *) ((arg1)->scaldims);
  *(int **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_clooginfos_1names_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct clooginfos *arg1 = (struct clooginfos *) 0 ;
  CloogNames *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct clooginfos **)&jarg1; 
  result = (CloogNames *) ((arg1)->names);
  *(CloogNames **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_clooginfos_1options_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct clooginfos *arg1 = (struct clooginfos *) 0 ;
  CloogOptions *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct clooginfos **)&jarg1; 
  result = (CloogOptions *) ((arg1)->options);
  *(CloogOptions **)&jresult = result; 
  return jresult;
}


JNIEXPORT jlong JNICALL Java_cloog_CLooGJNI_new_1clooginfos(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct clooginfos *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct clooginfos *)(struct clooginfos *) calloc(1, sizeof(struct clooginfos));
  *(struct clooginfos **)&jresult = result; 
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_delete_1clooginfos(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct clooginfos *arg1 = (struct clooginfos *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct clooginfos **)&jarg1; 
  free((char *) arg1);
  
}


JNIEXPORT jstring JNICALL Java_cloog_CLooGJNI_pprint_1line(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4, jlong jarg5) {
  jstring jresult = 0 ;
  Matrix *arg1 = (Matrix *) 0 ;
  Matrix *arg2 = (Matrix *) 0 ;
  int arg3 ;
  int arg4 ;
  CloogInfos *arg5 = (CloogInfos *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Matrix **)&jarg1; 
  arg2 = *(Matrix **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = *(CloogInfos **)&jarg5; 
  result = (char *)pprint_line(arg1,arg2,arg3,arg4,arg5);
  if(result) jresult = (*jenv)->NewStringUTF(jenv, result);
  return jresult;
}


JNIEXPORT jstring JNICALL Java_cloog_CLooGJNI_pprint_1minmax(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4, jint jarg5, jlong jarg6) {
  jstring jresult = 0 ;
  Matrix *arg1 = (Matrix *) 0 ;
  Matrix *arg2 = (Matrix *) 0 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  CloogInfos *arg6 = (CloogInfos *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Matrix **)&jarg1; 
  arg2 = *(Matrix **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (int)jarg5; 
  arg6 = *(CloogInfos **)&jarg6; 
  result = (char *)pprint_minmax(arg1,arg2,arg3,arg4,arg5,arg6);
  if(result) jresult = (*jenv)->NewStringUTF(jenv, result);
  return jresult;
}


JNIEXPORT void JNICALL Java_cloog_CLooGJNI_pprint(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jint jarg4, jint jarg5, jint jarg6, jlong jarg7) {
  FILE *arg1 = (FILE *) 0 ;
  CloogLoop *arg2 = (CloogLoop *) 0 ;
  Matrix *arg3 = (Matrix *) 0 ;
  int arg4 ;
  int arg5 ;
  int arg6 ;
  CloogInfos *arg7 = (CloogInfos *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(CloogLoop **)&jarg2; 
  arg3 = *(Matrix **)&jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (int)jarg5; 
  arg6 = (int)jarg6; 
  arg7 = *(CloogInfos **)&jarg7; 
  pprint(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
}


#ifdef __cplusplus
}
#endif

